"""
gateway.py

Master FastAPI gateway for the Financial Crime & Insider Risk Intelligence Platform.
Orchestrates Neo4j (graph patterns), the ML Anomaly Engine (:8001) and the local Qwen
model on llama-server (:8080), and serves the React dashboard under ``/api/v1``
(contract: ``frontend-dashboard/src/api/client.js``).

LLM narratives are slow relative to a UI request, so they are generated by a single
background worker (llama-server has one slot) in priority order: the alert a reviewer
opens jumps the queue; CRITICAL/HIGH alerts are pre-generated after the alert book builds.
"""

import asyncio
import itertools
import json
import logging
import time
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import httpx
from fastapi import APIRouter, FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from pydantic import BaseModel, Field
from starlette.concurrency import run_in_threadpool

from alert_engine import AlertEngine, AlertRecord
from config import settings
from graph_queries import ThreatDetectionEngine
from llm_explainer import Explanation, LlamaExplainer

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger("gateway")


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ====================================================================== LLM worker

class NarrativeQueue:
    """Single-consumer priority queue in front of llama-server with per-alert result caching."""

    def __init__(self, explainer: LlamaExplainer):
        self.explainer = explainer
        self.queue: asyncio.PriorityQueue = asyncio.PriorityQueue()
        self.futures: Dict[str, asyncio.Future] = {}
        self.evidence: Dict[str, Dict[str, Any]] = {}
        self._seq = itertools.count()
        self._worker: Optional[asyncio.Task] = None

    def start(self) -> None:
        self._worker = asyncio.create_task(self._run())

    async def stop(self) -> None:
        if self._worker:
            self._worker.cancel()

    def request(self, alert_id: str, evidence: Dict[str, Any], priority: int) -> asyncio.Future:
        """Return the (possibly already finished) future for this alert's narrative."""
        future = self.futures.get(alert_id)
        if future is not None and not (future.done() and future.exception()):
            if not future.done() and priority == 0:
                self.queue.put_nowait((0, next(self._seq), alert_id))  # bump; stale entries are skipped
            return future
        future = asyncio.get_running_loop().create_future()
        self.futures[alert_id] = future
        self.evidence[alert_id] = evidence
        self.queue.put_nowait((priority, next(self._seq), alert_id))
        return future

    def cached(self, alert_id: str) -> Optional[Explanation]:
        future = self.futures.get(alert_id)
        return future.result() if future and future.done() and not future.exception() else None

    async def _run(self) -> None:
        while True:
            _, _, alert_id = await self.queue.get()
            future = self.futures.get(alert_id)
            if future is None or future.done():
                continue
            started = time.perf_counter()
            try:
                result = await self.explainer.generate(self.evidence[alert_id])
                logger.info(f"LLM narrative for {alert_id} in {time.perf_counter() - started:.1f}s")
                future.set_result(result)
            except Exception as exc:  # noqa: BLE001 - any LLM failure falls back to rules
                logger.warning(f"LLM narrative for {alert_id} failed: {exc!r}")
                future.set_exception(exc)
                future.exception()  # mark retrieved; a later request retries


# ====================================================================== app state

class State:
    db: ThreatDetectionEngine
    engine: AlertEngine
    narratives: NarrativeQueue
    build_lock: asyncio.Lock
    build_error: Optional[str] = None
    investigations: Dict[str, Dict[str, Any]] = {}


state = State()


async def _db_call(name: str, *args: Any) -> Any:
    return await run_in_threadpool(getattr(state.db, name), *args)


async def build_alert_book(force: bool = False) -> Dict[str, AlertRecord]:
    """Run detectors + ML fusion once (or again on refresh); keeps case state across refreshes."""
    async with state.build_lock:
        if state.engine.alerts and not force:
            return state.engine.alerts
        started = time.perf_counter()
        try:
            alerts = await run_in_threadpool(state.engine.detect)
            await state.engine.score_with_ml(alerts, settings.ML_SERVICE_URL, _db_call)
            state.engine.transactions_scanned = await _db_call("count_transactions")
        except Exception as exc:
            state.build_error = f"{type(exc).__name__}: {exc}"
            logger.error(f"Alert build failed: {state.build_error}")
            raise HTTPException(status_code=503, detail=f"Graph database unavailable: {exc}") from exc
        for alert_id, alert in alerts.items():  # preserve reviewer actions
            previous = state.engine.alerts.get(alert_id)
            if previous:
                alert.status, alert.assigned_to = previous.status, previous.assigned_to
                alert.assigned_at, alert.notes = previous.assigned_at, previous.notes
        state.engine.alerts = alerts
        state.engine.built_at = _now()
        state.investigations.clear()
        state.build_error = None
        levels = {lvl: sum(a.risk_level == lvl for a in alerts.values()) for lvl in ("CRITICAL", "HIGH", "MEDIUM", "LOW")}
        logger.info(f"Built {len(alerts)} alerts in {time.perf_counter() - started:.1f}s: {levels}")
        return alerts


async def prewarm_narratives() -> None:
    """Queue LLM narratives for the most serious alerts so they're ready when opened."""
    try:
        alerts = await build_alert_book()
    except HTTPException:
        return
    ranked = sorted(alerts.values(), key=lambda a: -a.composite_score)
    for priority, alert in enumerate(a for a in ranked if a.risk_level in ("CRITICAL", "HIGH")):
        investigation = await get_investigation_bundle(alert)
        state.narratives.request(alert.alert_id, investigation["evidence"], priority + 1)


async def get_alert(alert_id: str) -> AlertRecord:
    alerts = await build_alert_book()
    alert = alerts.get(alert_id)
    if alert is None:
        raise HTTPException(status_code=404, detail=f"Alert {alert_id} not found.")
    return alert


async def get_investigation_bundle(alert: AlertRecord) -> Dict[str, Any]:
    bundle = state.investigations.get(alert.alert_id)
    if bundle is None:
        bundle = await run_in_threadpool(state.engine.build_investigation, alert)
        state.investigations[alert.alert_id] = bundle
    return bundle


async def get_explanation(alert: AlertRecord, evidence: Dict[str, Any], wait: float) -> Explanation:
    """LLM narrative if ready within ``wait`` seconds, else the rule-based explanation."""
    future = state.narratives.request(alert.alert_id, evidence, priority=0)
    try:
        return await asyncio.wait_for(asyncio.shield(future), timeout=wait)
    except asyncio.TimeoutError:
        note = "AI narrative is still generating; reopen the alert shortly"
    except Exception as exc:  # noqa: BLE001
        note = f"AI narrative unavailable: {type(exc).__name__}"
    return LlamaExplainer.rule_based(evidence, note)


@asynccontextmanager
async def lifespan(application: FastAPI):
    state.db = ThreatDetectionEngine(settings.NEO4J_URI, settings.NEO4J_USER, settings.NEO4J_PASSWORD)
    state.engine = AlertEngine(state.db, settings)
    state.narratives = NarrativeQueue(
        LlamaExplainer(settings.LLM_BASE_URL, settings.LLM_MODEL, settings.LLM_TIMEOUT_SECONDS)
    )
    state.build_lock = asyncio.Lock()
    state.narratives.start()
    prewarm = asyncio.create_task(prewarm_narratives())
    logger.info("Gateway services initialized.")
    yield
    prewarm.cancel()
    await state.narratives.stop()
    state.db.close()


app = FastAPI(
    title="FinCrime & Insider Risk Gateway API",
    description="Orchestration layer connecting Neo4j, ML Engine, and Local LLM.",
    version="2.0.0",
    lifespan=lifespan,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["Content-Disposition", "X-Request-ID"],
)
api = APIRouter(prefix="/api/v1")


# ====================================================================== models

class AssignCaseRequest(BaseModel):
    reviewer_id: str = Field(..., min_length=1, description="ID of the compliance reviewer")


class FreezeRequest(BaseModel):
    account_ids: List[str] = Field(..., min_length=1)


class EscalateRequest(BaseModel):
    note: str = ""


# ====================================================================== endpoints

@api.get("/alerts")
async def list_alerts(
    status: Optional[str] = None,
    risk_level: Optional[str] = None,
    limit: int = Query(100, ge=1, le=1000),
    refresh: bool = False,
) -> List[Dict[str, Any]]:
    """Alert queue, most severe first."""
    alerts = await build_alert_book(force=refresh)
    rows = [a for a in alerts.values()
            if (not status or a.status == status.upper()) and (not risk_level or a.risk_level == risk_level.upper())]
    rows.sort(key=lambda a: -a.composite_score)
    return [a.to_api() for a in rows[:limit]]


@api.get("/alerts/{alert_id}/investigation")
async def investigate_alert(alert_id: str) -> Dict[str, Any]:
    """Graph, timeline and explanation for one alert."""
    alert = await get_alert(alert_id)
    bundle = await get_investigation_bundle(alert)
    explanation = await get_explanation(alert, bundle["evidence"], settings.LLM_INLINE_WAIT_SECONDS)
    return {
        "alert": alert.to_api(),
        "graph": bundle["graph"],
        "explanation": explanation,
        "timeline": bundle["timeline"],
        "associated_account_ids": bundle["associated_account_ids"],
        "fraud_window": bundle["fraud_window"],
    }


@api.post("/cases/{case_id}/assign")
async def assign_case(case_id: str, request: AssignCaseRequest) -> Dict[str, Any]:
    alert = await get_alert(case_id)
    alert.assigned_to = request.reviewer_id
    alert.assigned_at = _now()
    if alert.status == "OPEN":
        alert.status = "ASSIGNED"
    alert.notes.append(f"{alert.assigned_at} assigned to {request.reviewer_id}")
    return {"case_id": case_id, "assigned_to": alert.assigned_to, "status": alert.status,
            "assigned_at": alert.assigned_at}


@api.post("/cases/{case_id}/freeze")
async def freeze_case_accounts(case_id: str, request: FreezeRequest) -> Dict[str, Any]:
    alert = await get_alert(case_id)
    unknown = set(request.account_ids) - alert.account_ids
    if unknown:
        raise HTTPException(status_code=400, detail=f"Accounts not linked to this case: {sorted(unknown)[:5]}")
    frozen = await _db_call("freeze_accounts", request.account_ids)
    alert.status = "FROZEN"
    alert.notes.append(f"{_now()} froze {len(frozen)} accounts")
    state.investigations.pop(case_id, None)
    return {"case_id": case_id, "status": alert.status, "affected_account_ids": frozen,
            "message": f"{len(frozen)} account(s) set to FROZEN in the graph."}


@api.post("/cases/{case_id}/escalate")
async def escalate_case(case_id: str, request: EscalateRequest) -> Dict[str, Any]:
    alert = await get_alert(case_id)
    alert.status = "ESCALATED"
    alert.notes.append(f"{_now()} escalated: {request.note}".rstrip(": "))
    return {"case_id": case_id, "status": alert.status, "affected_account_ids": [],
            "message": "Case escalated to the compliance lead."}


@api.get("/cases/{case_id}/dossier")
async def export_dossier(case_id: str, format: str = Query("pdf", pattern="^(pdf|json)$")) -> Response:
    """Evidence dossier; waits longer than the UI view for the LLM narrative."""
    alert = await get_alert(case_id)
    bundle = await get_investigation_bundle(alert)
    explanation = await get_explanation(alert, bundle["evidence"], wait=75.0)
    dossier = {
        "case_id": case_id,
        "generated_at": _now(),
        "alert": alert.to_api(),
        "case_notes": alert.notes,
        "explanation": explanation,
        "associated_account_ids": bundle["associated_account_ids"],
        "fraud_window": bundle["fraud_window"],
        "timeline": bundle["timeline"],
        "evidence": {k: v for k, v in bundle["evidence"].items() if k != "timeline"},
    }
    if format == "json":
        body, media = json.dumps(dossier, indent=2, default=str).encode(), "application/json"
    else:
        from dossier_pdf import render_pdf
        body, media = await run_in_threadpool(render_pdf, dossier), "application/pdf"
    filename = f"evidence-dossier-{case_id}.{format}"
    return Response(body, media_type=media, headers={"Content-Disposition": f'attachment; filename="{filename}"'})


@api.get("/reviewers")
async def list_reviewers() -> List[Dict[str, Any]]:
    alerts = await build_alert_book()
    flagged = {a.emp_id for a in alerts.values() if a.emp_id and a.risk_level in ("CRITICAL", "HIGH")}
    return await _db_call("list_reviewers", sorted(flagged))


async def _probe(url: str) -> Dict[str, Any]:
    started = time.perf_counter()
    try:
        async with httpx.AsyncClient(timeout=2.5) as client:
            response = await client.get(url)
        latency = round((time.perf_counter() - started) * 1000, 1)
        detail = response.json() if response.headers.get("content-type", "").startswith("application/json") else {}
        return {"online": response.status_code == 200, "latency_ms": latency,
                "detail": detail.get("status") or f"HTTP {response.status_code}"}
    except httpx.HTTPError as exc:
        return {"online": False, "latency_ms": None, "detail": type(exc).__name__}


@api.get("/system/status")
async def system_status() -> Dict[str, Any]:
    ml, llm = await asyncio.gather(
        _probe(f"{settings.ML_SERVICE_URL}/health"), _probe(f"{settings.LLM_BASE_URL}/health")
    )
    started = time.perf_counter()
    try:
        await _db_call("ping")
        graph = {"online": True, "latency_ms": round((time.perf_counter() - started) * 1000, 1),
                 "detail": settings.NEO4J_URI}
    except Exception as exc:  # noqa: BLE001
        graph = {"online": False, "latency_ms": None, "detail": type(exc).__name__}
    alerts = list(state.engine.alerts.values())
    ml.update(label="ML Engine")
    llm.update(label=f"LLM ({settings.LLM_MODEL})")
    graph.update(label="Neo4j Graph")
    return {
        "nodes": {"ml": ml, "llm": llm, "graph": graph},
        "metrics": {
            "open_alerts": sum(a.status == "OPEN" for a in alerts),
            "active_cases": sum(a.status in ("ASSIGNED", "ESCALATED", "FROZEN") for a in alerts),
            "critical_alerts": sum(a.risk_level == "CRITICAL" for a in alerts),
            "transactions_scanned": state.engine.transactions_scanned,
            "flagged_employees": len({a.emp_id for a in alerts if a.emp_id and a.risk_level in ("CRITICAL", "HIGH")}),
        },
        "checked_at": _now(),
    }


app.include_router(api)


@app.get("/health")
async def health() -> Dict[str, Any]:
    return {"status": "ok", "alerts_built": bool(state.engine.alerts), "built_at": state.engine.built_at,
            "build_error": state.build_error}


if __name__ == "__main__":
    import uvicorn

    logger.info(f"Starting API Gateway on port {settings.API_PORT}...")
    uvicorn.run("gateway:app", host=settings.API_HOST, port=settings.API_PORT)
